[package]
name = "rustunicodetests"
version = "0.1.0"
authors = ["jeremymarch <jmarch@gradcenter.cuny.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "0.1.17"
bitflags = "1.2.1"

[profile.release]
opt-level = "z"
